title: Il Polemico
description: 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "ilpolemico98.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Il Polemico # add your name
author-img: 
about-author: 
social-email: ilpolemico98@libero.it # add your Email address

# Disqus
discus-identifier: ilpolemico98 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
